src/main/java/org/openrewrite/github/ActionsSetupJavaAdoptOpenJDKToTemurin.java

See [openrewrite/rewrite#977] and [openrewrite/rewrite#1062] 👍

Use matcher with regex filter on ActionsSetupJavaAdoptOpenJDKToTemurin

---

suppressions.xml

Related to: https://github.com/moderneinc/dependency-vulnerability-reports/issues/478

chore: update snake-yaml false positive

---

src/main/java/org/openrewrite/github/ReplaceRunners.java
src/test/kotlin/org/openrewrite/github/ReplaceRunnersTest.kt

Closes https://github.com/openrewrite/rewrite-github-actions/issues/25

Add replace runners recipe

---

src/main/java/org/openrewrite/github/RemoveAllCronTriggers.java
src/test/kotlin/org/openrewrite/github/RemoveAllCronTriggerTest.kt

Remove all cron triggers

---

src/main/java/org/openrewrite/github/PreferTemurinDistributions.java
src/test/java/org/openrewrite/github/PreferTemurinDistributionsTest.java

add PreferTemurinDistributions recipe

---

src/main/java/org/openrewrite/github/PreferTemurinDistributions.java

Right now there's an unnecessary new line and random period in it. Let's remove both of those to better match other recipes.

Fix Temurin Recipe Description

---

src/main/java/org/openrewrite/github/AddCronTrigger.java
src/test/java/org/openrewrite/github/AddCronTriggerTest.java

feat: add support for randon non-standard cron expressions

---

src/main/java/org/openrewrite/github/AddCronTrigger.java
src/test/java/org/openrewrite/github/AddCronTriggerTest.java

feat: add option to configure the workflow files to match for the AddCronTrigger recipe

---

src/test/java/org/openrewrite/github/SetupJavaAdoptOpenj9ToSemeruTest.java

Use this link to re-run the recipe: https://app.moderne.io/recipes/org.openrewrite.java.recipes.SelectRecipeExamples?organizationId=T3BlblJld3JpdGU%3D

refactor: Automatically select recipe examples from the unit test cases of a recipe

---

src/main/java/org/openrewrite/github/AddCronTrigger.java
src/test/java/org/openrewrite/github/AddCronTriggerTest.java

Fixes #86 
Fixes https://github.com/openrewrite/rewrite-spring/issues/391

Delay use of AddCronTrigger fields to prevent NPE

---

src/main/java/org/openrewrite/github/SetupJavaUpgradeJavaVersion.java
src/test/java/org/openrewrite/github/SetupJavaUpgradeJavaVersionTest.java

feat: update base jdk to 21

---

gradle/wrapper/gradle-wrapper.properties
gradlew

Upgraded Gradle to 8.4 for Java 21 compatibility
Improved Java 21 compatibility

feat: upgrade gradle version to 8.4 for Java 21 compatibility

---

src/main/java/org/openrewrite/github/ChangeActionVersion.java
src/test/java/org/openrewrite/github/ChangeActionVersionTest.java

Added `ChangeActionVersion` recipe.
Fixes #23
Deliberately did not make workflow file customizable; folks can use yaml preconditions.
Nor did I check for existing values before overriding; we're changing, not updating here.
Folks could already call `ChangeValue` with declarative yaml recipes + preconditions, but not yet via the platform (soon), and not very easy to discover for folks. This recipe can then serve as a template for some of the other suggested recipes here.
- #23

Change the version of a GitHub Action

---

src/main/java/org/openrewrite/github/SetupJavaDistributionReplacerVisitor.java
src/test/java/org/openrewrite/github/PreferTemurinDistributionsTest.java

add support for setup-java v4
Github Action [setup-java](https://github.com/actions/setup-java/releases) v4 is the latest version
n/a
n/a
n/a
n/a

support setup-java v4

---

src/test/java/org/openrewrite/github/SetupJavaUpgradeJavaVersionTest.java

enhanced unit test for SetupJavaUpgradeJavaVersion
To verify that the recipe will modify all occurrences of 'setup-java' in a workflow
n/a
n/a
n/a
n/a

enhance unit test for SetupJavaUpgradeJavaVersion

---

src/main/java/org/openrewrite/github/PreferSecretsInheritWorkflow.java
src/test/java/org/openrewrite/github/PreferSecretsInheritWorkflowTest.java

New recipe
This addresses https://github.com/openrewrite/rewrite-github-actions/issues/89
Is there a way to simplify the JsonPathMatcher expression?

Add recipe to use `secrets: inherit` if possible

---

src/main/resources/META-INF/rewrite/github.yml

adds new recipe
I want to inventory secrets actually used so I can remove unused secrets and ensure auto rotation of ones in use.
I also want to use the data table for these options specifically to make a distribution visualization

feat: add find GH action secrets in use

---

src/main/java/org/openrewrite/github/AddCronTrigger.java
src/main/java/org/openrewrite/github/AutoCancelInProgressWorkflow.java
src/main/java/org/openrewrite/github/SetupJavaUpgradeJavaVersion.java
src/main/java/org/openrewrite/github/package-info.java

Use this link to re-run the recipe: https://app.moderne.io/builder/gW3xaSLWV?organizationId=T3BlblJld3JpdGU%3D

Migrate to JSpecify from OpenRewrite JSR-305 meta-annotations

---

src/main/java/org/openrewrite/github/PreferSecretsInheritWorkflow.java

Use this link to re-run the recipe: [app.moderne](https://app.moderne.io/recipes/org.openrewrite.java.AddNullMethodArgument?organizationId=TW9kZXJuZQ%3D%3D#defaults%3DW3sibmFtZSI6Im1ldGhvZFBhdHRlcm4iLCJ2YWx1ZSI6Im9yZy5vcGVucmV3cml0ZS55YW1sLnRyZWUuWWFtbC5TY2FsYXIgPGNvbnN0cnVjdG9yPihqYXZhLnV0aWwuVVVJRCwgamF2YS5sYW5nLlN0cmluZywgb3JnLm9wZW5yZXdyaXRlLm1hcmtlci5NYXJrZXJzLCBvcmcub3BlbnJld3JpdGUueWFtbC50cmVlLllhbWwuU2NhbGFyLlN0eWxlLCBvcmcub3BlbnJld3JpdGUueWFtbC50cmVlLllhbWwuQW5jaG9yLCBqYXZhLmxhbmcuU3RyaW5nKSJ9LHsibmFtZSI6ImFyZ3VtZW50SW5kZXgiLCJ2YWx1ZSI6IjQifSx7Im5hbWUiOiJwYXJhbWV0ZXJUeXBlIiwidmFsdWUiOiJvcmcub3BlbnJld3JpdGUueWFtbC50cmVlLllhbWwuVGFnIn0seyJuYW1lIjoicGFyYW1ldGVyTmFtZSIsInZhbHVlIjoidGFnIn0seyJuYW1lIjoiZXhwbGljaXRDYXN0IiwidmFsdWUiOiJGYWxzZSJ9XQ%3D%3D)
Adapting to new interface wrt …

Adapt to new Yaml.Tag interface

---

src/main/java/org/openrewrite/github/UpgradeSlackNotificationVersion2.java

Update MergeYaml constructors
- https://github.com/openrewrite/rewrite/pull/5036
- Broken fix in main after applying: https://github.com/openrewrite/rewrite-github-actions/commit/645f3196012d11b66926dee8e7871d1b871c1fe8

refactor: MergeYaml argument

---

src/main/java/org/openrewrite/github/AddCronTrigger.java
src/main/java/org/openrewrite/github/SetupJavaCaching.java
src/main/java/org/openrewrite/github/UpgradeSlackNotificationVersion2.java

Adapting code to changes in upstream constructors done in https://github.com/openrewrite/rewrite/pull/5324
Fix broken CI.

Fix MergeYaml constructor calls
